select	a11.ID_ANO_LANC  ID_ANO,
	a11.ID_MES_LANC  ID_MES,
	a11.ID_DIA_LANC  ID_DIA,
	max(a116.NO_DIA_COMPLETO)  NO_DIA_COMPLETO,
	a14.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
	max(a130.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	max(a130.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
	a114.ID_FONTE_RECURSO  ID_FONTE_RECURSO,
	max(a129.CO_FONTE_RECURSO)  CO_FONTE_RECURSO,
	max(a129.NO_FONTE_RECURSO)  NO_FONTE_RECURSO,
	a112.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
	max(a128.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
	max(a128.NO_ORGAO_MAXI)  NO_ORGAO_MAXI,
	a17.ID_ORGAO_UG  ID_ORGAO,
	max(a127.CO_ORGAO)  CO_ORGAO,
	max(a127.NO_ORGAO)  NO_ORGAO,
	a15.ID_DOCUMENTO  ID_DOCUMENTO,
	a15.TX_OBSERVACAO  TX_OBSERVACAO,
	a11.ID_FONTE_RECURSO_DETA  ID_FONTE_RECURSO_DETA,
	max(a114.CO_FONTE_RECURSO_DETA)  CO_FONTE_RECURSO_DETA,
	max(a114.NO_FONTE_RECURSO_DETA)  NO_FONTE_RECURSO_DETA,
	a11.ID_FUNCAO_PT  ID_FUNCAO_PT,
	max(a118.NO_FUNCAO_PT)  ID_FUNCAO_PT0,
	a11.ID_SUBFUNCAO_PT  ID_SUBFUNCAO_PT,
	max(a123.NO_SUBFUNCAO_PT)  NO_SUBFUNCAO_PT,
	a11.ID_PROGRAMA_PT  ID_PROGRAMA_PT,
	max(a121.NO_PROGRAMA_PT)  NO_PROGRAMA_PT,
	a11.ID_ACAO_PT  ID_ACAO_PT,
	max(a115.NO_ACAO_PT)  NO_ACAO_PT,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
	max(a119.NO_GRUPO_DESPESA_NADE)  NO_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE  ID_MOAP_NADE,
	max(a120.CO_MOAP_NADE)  CO_MOAP_NADE,
	max(a120.NO_MOAP_NADE)  NO_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
	max(a117.CO_ELEMENTO_DESPESA_NADE)  CO_NATUREZA_DESPESA,
	max(a117.NO_ELEMENTO_DESPESA_NADE)  NO_NATUREZA_DESPESA,
	a11.ID_DOCUMENTO_CCOR  ID_DOCUMENTO0,
	a113.ID_ANO_EMISSAO_DOC  ID_ANO0,
	a18.ID_ORGAO_UO  ID_ORGAO0,
	max(a125.CO_ORGAO)  CO_ORGAO0,
	max(a125.NO_ORGAO)  NO_ORGAO0,
	a110.ID_ORGAO_MAXI  ID_ORGAO_MAXI0,
	max(a126.CO_ORGAO_MAXI)  CO_ORGAO_MAXI0,
	max(a126.NO_ORGAO_MAXI)  NO_ORGAO_MAXI0,
	a16.ID_IN_RESULTADO_EOF  ID_IN_RESULTADO_EOF,
	max(a122.NO_IN_RESULTADO_EOF)  NO_IN_RESULTADO_EOF,
	a16.SN_EXCECAO_DECRETO  SN_EXCECAO_DECRETO,
	a17.ID_UG  ID_UG_EXEC,
	max(a124.CO_UG)  CO_UG,
	max(a124.NO_UG)  NO_UG,
	sum(((a11.VA_MOVIMENTO_LIQUIDO * a14.IN_OPERACAO_EXPRESSAO) * a13.PE_TAXA))  SALDORITEMINFORMAO
from	WF_LANCAMENTO	a11
	join	WD_MOEDA	a12
	  on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
	join	WD_TAXA_CAMBIO_MENSAL	a13
	  on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
	join	WD_ITEM_DECODIFICADO_CCON	a14
	  on 	(a11.ID_ANO_LANC = a14.ID_ANO_ITEM_CONTA and 
	a11.ID_CONTA_CONTABIL_LANC = a14.ID_CONTA_CONTABIL)
	join	WD_DOCUMENTO	a15
	  on 	(a11.ID_ANO_LANC = a15.ID_ANO_EMISSAO_DOC and 
	a11.ID_DOCUMENTO_LANC = a15.ID_DOCUMENTO)
	join	WD_CELULA_ORCAMENTARIA	a16
	  on 	(a11.ID_ANO_LANC = a16.ID_ANO_CEOR and 
	a11.ID_CELULA_ORCAMENTARIA_SK = a16.ID_CELULA_ORCAMENTARIA_SK)
	join	WD_UG_EXERCICIO	a17
	  on 	(a11.ID_ANO_LANC = a17.ID_ANO and 
	a11.ID_UG_EXEC = a17.ID_UG)
	join	WD_UO_EXERCICIO	a18
	  on 	(a11.ID_ANO_LANC = a18.ID_ANO and 
	a11.ID_UO = a18.ID_UO)
	join	WD_ORGAO_EXERCICIO	a19
	  on 	(a18.ID_ANO = a19.ID_ANO and 
	a18.ID_ORGAO_UO = a19.ID_ORGAO)
	join	WD_ORGAO_SUPE_EXERCICIO	a110
	  on 	(a19.ID_ANO = a110.ID_ANO and 
	a19.ID_ORGAO_SUPE = a110.ID_ORGAO_SUPE)
	join	WD_ORGAO_EXERCICIO	a111
	  on 	(a17.ID_ANO = a111.ID_ANO and 
	a17.ID_ORGAO_UG = a111.ID_ORGAO)
	join	WD_ORGAO_SUPE_EXERCICIO	a112
	  on 	(a111.ID_ANO = a112.ID_ANO and 
	a111.ID_ORGAO_SUPE = a112.ID_ORGAO_SUPE)
	join	WD_DOC_NE	a113
	  on 	(a11.ID_DOCUMENTO_CCOR = a113.ID_DOC_NE)
	join	WD_FONTE_RECURSO_DETA	a114
	  on 	(a11.ID_FONTE_RECURSO_DETA = a114.ID_FONTE_RECURSO_DETA)
	join	WD_ACAO_PT	a115
	  on 	(a11.ID_ACAO_PT = a115.ID_ACAO_PT)
	join	WD_DIA	a116
	  on 	(a11.ID_ANO_LANC = a116.ID_ANO and 
	a11.ID_DIA_LANC = a116.ID_DIA and 
	a11.ID_MES_LANC = a116.ID_MES)
	join	WD_ELEMENTO_DESPESA_NADE	a117
	  on 	(a11.ID_ELEMENTO_DESPESA_NADE = a117.ID_ELEMENTO_DESPESA_NADE)
	join	WD_FUNCAO_PT	a118
	  on 	(a11.ID_FUNCAO_PT = a118.ID_FUNCAO_PT)
	join	WD_GRUPO_DESPESA_NADE	a119
	  on 	(a11.ID_GRUPO_DESPESA_NADE = a119.ID_GRUPO_DESPESA_NADE)
	join	WD_MODALIDADE_APLICACAO_NADE	a120
	  on 	(a11.ID_MOAP_NADE = a120.ID_MOAP_NADE)
	join	WD_PROGRAMA_PT	a121
	  on 	(a11.ID_PROGRAMA_PT = a121.ID_PROGRAMA_PT)
	join	WD_IN_RESULTADO_EOF_CEOR	a122
	  on 	(a16.ID_IN_RESULTADO_EOF = a122.ID_IN_RESULTADO_EOF)
	join	WD_SUBFUNCAO_PT	a123
	  on 	(a11.ID_SUBFUNCAO_PT = a123.ID_SUBFUNCAO_PT)
	join	WD_UG	a124
	  on 	(a17.ID_UG = a124.ID_UG)
	join	WD_ORGAO	a125
	  on 	(a18.ID_ORGAO_UO = a125.ID_ORGAO)
	join	WD_ORGAO_MAXI	a126
	  on 	(a110.ID_ORGAO_MAXI = a126.ID_ORGAO_MAXI)
	join	WD_ORGAO	a127
	  on 	(a17.ID_ORGAO_UG = a127.ID_ORGAO)
	join	WD_ORGAO_MAXI	a128
	  on 	(a112.ID_ORGAO_MAXI = a128.ID_ORGAO_MAXI)
	join	WD_FONTE_RECURSO	a129
	  on 	(a114.ID_FONTE_RECURSO = a129.ID_FONTE_RECURSO)
	join	WD_ITEM_INFORMACAO	a130
	  on 	(a14.ID_ITEM_INFORMACAO = a130.ID_ITEM_INFORMACAO)
where	(a112.ID_ORGAO_MAXI in (30000)
 and a14.ID_ITEM_INFORMACAO in (812)
 and a11.ID_ANO_LANC in (2017, 2018, 2019)
 and a13.ID_ANO = a11.ID_ANO_LANC
 and a13.ID_MES = a11.ID_MES_LANC)
group by	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a11.ID_DIA_LANC,
	a14.ID_ITEM_INFORMACAO,
	a114.ID_FONTE_RECURSO,
	a112.ID_ORGAO_MAXI,
	a17.ID_ORGAO_UG,
	a15.ID_DOCUMENTO,
	a15.TX_OBSERVACAO,
	a11.ID_FONTE_RECURSO_DETA,
	a11.ID_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT,
	a11.ID_PROGRAMA_PT,
	a11.ID_ACAO_PT,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a11.ID_DOCUMENTO_CCOR,
	a113.ID_ANO_EMISSAO_DOC,
	a18.ID_ORGAO_UO,
	a110.ID_ORGAO_MAXI,
	a16.ID_IN_RESULTADO_EOF,
	a16.SN_EXCECAO_DECRETO,
	a17.ID_UG