select	coalesce(pa11.ID_DOCUMENTO, pa12.ID_DOCUMENTO)  ID_DOCUMENTO,
	coalesce(pa11.ID_ANO_EMISSAO_DOC, pa12.ID_ANO_EMISSAO_DOC)  ID_ANO_EMISSAO_DOC,
	coalesce(pa11.ID_FONTE_RECURSO, pa12.ID_FONTE_RECURSO)  ID_FONTE_RECURSO,
	max(a13.CO_FONTE_RECURSO)  CO_FONTE_RECURSO,
	max(a13.NO_FONTE_RECURSO)  NO_FONTE_RECURSO,
	coalesce(pa11.ID_VINCULACAO_PAGAMENTO, pa12.ID_VINCULACAO_PAGAMENTO)  ID_VINCULACAO_PAGAMENTO,
	max(a15.NO_VINCULACAO_PAGAMENTO)  NO_VINCULACAO_PAGAMENTO,
	coalesce(pa11.ID_ANO_LANC, pa12.ID_ANO_LANC)  ID_ANO_LANC,
	coalesce(pa11.ID_MES_LANC, pa12.ID_MES_LANC)  ID_MES_LANC,
	max(a14.SG_MES_COMPLETO)  SG_MES_COMPLETO,
	max(pa11.SALDOANTRCONTACONTBIL)  SALDOANTRCONTACONTBIL,
	max(pa12.SALDORCONTACONTBIL)  SALDORCONTACONTBIL
from	(select	a11.ID_VINCULACAO_PAGAMENTO  ID_VINCULACAO_PAGAMENTO,
		a14.ID_ANO  ID_ANO_LANC,
		a14.ID_MES  ID_MES_LANC,
		a16.ID_FONTE_RECURSO  ID_FONTE_RECURSO,
		a11.ID_DOCUMENTO_LANC  ID_DOCUMENTO,
		a11.ID_ANO_LANC  ID_ANO_EMISSAO_DOC,
		sum((a11.VA_MOVIMENTO_LIQUIDO * a13.PE_TAXA_ANTERIOR))  SALDOANTRCONTACONTBIL
	from	WF_LANCAMENTO	a11
		join	WD_MOEDA	a12
		  on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
		join	WD_TAXA_CAMBIO_MENSAL	a13
		  on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
		join	WA_MES_ACUM	a14
		  on 	(a11.ID_ANO_LANC = a14.ID_ANO_ACUM_ANO_SALDO and 
		a11.ID_MES_LANC = (a14.ID_MES_ACUM_ANO_SALDO - 1))
		join	WD_CONTA_CONTABIL_EXERCICIO	a15
		  on 	(a11.ID_ANO_LANC = a15.ID_ANO and 
		a11.ID_CONTA_CONTABIL_LANC = a15.ID_CONTA_CONTABIL)
		join	WD_FONTE_RECURSO_DETA	a16
		  on 	(a11.ID_FONTE_RECURSO_DETA = a16.ID_FONTE_RECURSO_DETA)
		join	WD_UG_EXERCICIO	a17
		  on 	(a11.ID_ANO_LANC = a17.ID_ANO and 
		a11.ID_UG_EXEC = a17.ID_UG)
		join	WD_ORGAO_EXERCICIO	a18
		  on 	(a17.ID_ANO = a18.ID_ANO and 
		a17.ID_ORGAO_UG = a18.ID_ORGAO)
		join	WD_ORGAO_SUPE_EXERCICIO	a19
		  on 	(a18.ID_ANO = a19.ID_ANO and 
		a18.ID_ORGAO_SUPE = a19.ID_ORGAO_SUPE)
		join	WD_MES	a110
		  on 	(a14.ID_ANO = a110.ID_ANO and 
		a14.ID_MES = a110.ID_MES)
	where	(a11.ID_ORCA_FISCAL_ORGAO_EXEC_H in (0)
	 and a110.SG_MES_COMPLETO = 'MAR/2019'
	 and a15.ID_CONTA_CONTABIL_DESTINO in (111122001, 111122003)
	 and a19.ID_ORGAO_MAXI in (32000)
	 and a13.ID_ANO = a110.ID_ANO
	 and a13.ID_MES = a110.ID_MES)
	group by	a11.ID_VINCULACAO_PAGAMENTO,
		a14.ID_ANO,
		a14.ID_MES,
		a16.ID_FONTE_RECURSO,
		a11.ID_DOCUMENTO_LANC,
		a11.ID_ANO_LANC
	)	pa11
	full outer join	(select	a11.ID_VINCULACAO_PAGAMENTO  ID_VINCULACAO_PAGAMENTO,
		a14.ID_ANO  ID_ANO_LANC,
		a14.ID_MES  ID_MES_LANC,
		a16.ID_FONTE_RECURSO  ID_FONTE_RECURSO,
		a11.ID_DOCUMENTO_LANC  ID_DOCUMENTO,
		a11.ID_ANO_LANC  ID_ANO_EMISSAO_DOC,
		sum((a11.VA_MOVIMENTO_LIQUIDO * a13.PE_TAXA))  SALDORCONTACONTBIL
	from	WF_LANCAMENTO	a11
		join	WD_MOEDA	a12
		  on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
		join	WD_TAXA_CAMBIO_MENSAL	a13
		  on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
		join	WA_MES_ACUM	a14
		  on 	(a11.ID_ANO_LANC = a14.ID_ANO_ACUM_ANO_SALDO and 
		a11.ID_MES_LANC = a14.ID_MES_ACUM_ANO_SALDO)
		join	WD_CONTA_CONTABIL_EXERCICIO	a15
		  on 	(a11.ID_ANO_LANC = a15.ID_ANO and 
		a11.ID_CONTA_CONTABIL_LANC = a15.ID_CONTA_CONTABIL)
		join	WD_FONTE_RECURSO_DETA	a16
		  on 	(a11.ID_FONTE_RECURSO_DETA = a16.ID_FONTE_RECURSO_DETA)
		join	WD_UG_EXERCICIO	a17
		  on 	(a11.ID_ANO_LANC = a17.ID_ANO and 
		a11.ID_UG_EXEC = a17.ID_UG)
		join	WD_ORGAO_EXERCICIO	a18
		  on 	(a17.ID_ANO = a18.ID_ANO and 
		a17.ID_ORGAO_UG = a18.ID_ORGAO)
		join	WD_ORGAO_SUPE_EXERCICIO	a19
		  on 	(a18.ID_ANO = a19.ID_ANO and 
		a18.ID_ORGAO_SUPE = a19.ID_ORGAO_SUPE)
		join	WD_MES	a110
		  on 	(a14.ID_ANO = a110.ID_ANO and 
		a14.ID_MES = a110.ID_MES)
	where	(a11.ID_ORCA_FISCAL_ORGAO_EXEC_H in (0)
	 and a110.SG_MES_COMPLETO = 'MAR/2019'
	 and a15.ID_CONTA_CONTABIL_DESTINO in (111122001, 111122003)
	 and a19.ID_ORGAO_MAXI in (32000)
	 and a13.ID_ANO = a110.ID_ANO
	 and a13.ID_MES = a110.ID_MES)
	group by	a11.ID_VINCULACAO_PAGAMENTO,
		a14.ID_ANO,
		a14.ID_MES,
		a16.ID_FONTE_RECURSO,
		a11.ID_DOCUMENTO_LANC,
		a11.ID_ANO_LANC
	)	pa12
	  on 	(pa11.ID_ANO_EMISSAO_DOC = pa12.ID_ANO_EMISSAO_DOC and 
	pa11.ID_ANO_LANC = pa12.ID_ANO_LANC and 
	pa11.ID_DOCUMENTO = pa12.ID_DOCUMENTO and 
	pa11.ID_FONTE_RECURSO = pa12.ID_FONTE_RECURSO and 
	pa11.ID_MES_LANC = pa12.ID_MES_LANC and 
	pa11.ID_VINCULACAO_PAGAMENTO = pa12.ID_VINCULACAO_PAGAMENTO)
	join	WD_FONTE_RECURSO	a13
	  on 	(coalesce(pa11.ID_FONTE_RECURSO, pa12.ID_FONTE_RECURSO) = a13.ID_FONTE_RECURSO)
	join	WD_MES	a14
	  on 	(coalesce(pa11.ID_ANO_LANC, pa12.ID_ANO_LANC) = a14.ID_ANO and 
	coalesce(pa11.ID_MES_LANC, pa12.ID_MES_LANC) = a14.ID_MES)
	join	WD_VINCULACAO_PAGAMENTO	a15
	  on 	(coalesce(pa11.ID_VINCULACAO_PAGAMENTO, pa12.ID_VINCULACAO_PAGAMENTO) = a15.ID_VINCULACAO_PAGAMENTO)
group by	coalesce(pa11.ID_DOCUMENTO, pa12.ID_DOCUMENTO),
	coalesce(pa11.ID_ANO_EMISSAO_DOC, pa12.ID_ANO_EMISSAO_DOC),
	coalesce(pa11.ID_FONTE_RECURSO, pa12.ID_FONTE_RECURSO),
	coalesce(pa11.ID_VINCULACAO_PAGAMENTO, pa12.ID_VINCULACAO_PAGAMENTO),
	coalesce(pa11.ID_ANO_LANC, pa12.ID_ANO_LANC),
	coalesce(pa11.ID_MES_LANC, pa12.ID_MES_LANC)