select	coalesce(pa11.ID_DOCUMENTO0, pa12.ID_DOCUMENTO0)  ID_DOCUMENTO,
	coalesce(pa11.ID_ANO_EMISSAO_DOC, pa12.ID_ANO_EMISSAO_DOC)  ID_ANO_EMISSAO_DOC,
	coalesce(pa11.ID_DOCUMENTO, pa12.ID_DOCUMENTO)  ID_DOCUMENTO0,
	coalesce(pa11.ID_ORGAO_MAXI0, pa12.ID_ORGAO_MAXI0)  ID_ORGAO_MAXI,
	max(a112.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
	max(a112.NO_ORGAO_MAXI)  NO_ORGAO_MAXI,
	coalesce(pa11.ID_FONTE_RECURSO, pa12.ID_FONTE_RECURSO)  ID_FONTE_RECURSO,
	max(a15.CO_FONTE_RECURSO)  CO_FONTE_RECURSO,
	max(a15.NO_FONTE_RECURSO)  NO_FONTE_RECURSO,
	coalesce(pa11.ID_GRUPO_DESPESA_NADE, pa12.ID_GRUPO_DESPESA_NADE)  ID_GRUPO_DESPESA_NADE,
	max(a16.NO_GRUPO_DESPESA_NADE)  NO_GRUPO_DESPESA_NADE,
	coalesce(pa11.ID_ELEMENTO_DESPESA_NADE, pa12.ID_ELEMENTO_DESPESA_NADE)  ID_ELEMENTO_DESPESA_NADE,
	max(a14.CO_ELEMENTO_DESPESA_NADE)  CO_NATUREZA_DESPESA,
	max(a14.NO_ELEMENTO_DESPESA_NADE)  NO_NATUREZA_DESPESA,
	coalesce(pa11.ID_PROGRAMA_PT, pa12.ID_PROGRAMA_PT)  ID_PROGRAMA_PT,
	max(a19.NO_PROGRAMA_PT)  NO_PROGRAMA_PT,
	coalesce(pa11.ID_ACAO_PT, pa12.ID_ACAO_PT)  ID_ACAO_PT,
	max(a13.NO_ACAO_PT)  NO_ACAO_PT,
	coalesce(pa11.ID_IN_RESULTADO_EOF, pa12.ID_IN_RESULTADO_EOF)  ID_IN_RESULTADO_EOF,
	max(a111.NO_IN_RESULTADO_EOF)  NO_IN_RESULTADO_EOF,
	coalesce(pa11.ID_IN_PRSE_CEOR, pa12.ID_IN_PRSE_CEOR)  ID_IN_PRSE_CEOR,
	max(a110.NO_IN_PRSE_CEOR)  NO_IN_PRSE_CEOR,
	coalesce(pa11.SN_EXCECAO_DECRETO, pa12.SN_EXCECAO_DECRETO)  SN_EXCECAO_DECRETO,
	coalesce(pa11.ID_ANO_LANC, pa12.ID_ANO_LANC)  ID_ANO_LANC,
	coalesce(pa11.ID_MES_LANC, pa12.ID_MES_LANC)  ID_MES_LANC,
	max(a18.SG_MES_COMPLETO)  SG_MES_COMPLETO,
	coalesce(pa11.ID_ORGAO_MAXI, pa12.ID_ORGAO_MAXI)  ID_ORGAO_MAXI0,
	max(a113.CO_ORGAO_MAXI)  CO_ORGAO_MAXI0,
	max(a113.NO_ORGAO_MAXI)  NO_ORGAO_MAXI0,
	coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO)  ID_ITEM_INFORMACAO,
	max(a17.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	max(a17.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
	max(pa11.SALDOANTRITEMINFORMAO)  SALDOANTRITEMINFORMAO,
	max(pa12.SALDORITEMINFORMAO)  SALDORITEMINFORMAO
from	(select	a113.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
		a110.ID_ORGAO_MAXI  ID_ORGAO_MAXI0,
		a16.ID_IN_RESULTADO_EOF  ID_IN_RESULTADO_EOF,
		a16.ID_IN_PRSE_CEOR  ID_IN_PRSE_CEOR,
		a11.ID_PROGRAMA_PT  ID_PROGRAMA_PT,
		a11.ID_DOCUMENTO_CCOR  ID_DOCUMENTO,
		a15.ID_ANO  ID_ANO_LANC,
		a15.ID_MES  ID_MES_LANC,
		a14.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
		a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
		a17.ID_FONTE_RECURSO  ID_FONTE_RECURSO,
		a16.SN_EXCECAO_DECRETO  SN_EXCECAO_DECRETO,
		a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
		a11.ID_DOCUMENTO_LANC  ID_DOCUMENTO0,
		a11.ID_ANO_LANC  ID_ANO_EMISSAO_DOC,
		a11.ID_ACAO_PT  ID_ACAO_PT,
		sum(((a11.VA_MOVIMENTO_LIQUIDO * a14.IN_OPERACAO_EXPRESSAO) * a13.PE_TAXA_ANTERIOR))  SALDOANTRITEMINFORMAO
	from	WF_LANCAMENTO	a11
		join	WD_MOEDA	a12
		  on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
		join	WD_TAXA_CAMBIO_MENSAL	a13
		  on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
		join	WD_ITEM_DECODIFICADO_CCON	a14
		  on 	(a11.ID_ANO_LANC = a14.ID_ANO_ITEM_CONTA and 
		a11.ID_CONTA_CONTABIL_LANC = a14.ID_CONTA_CONTABIL)
		join	WA_MES_ACUM	a15
		  on 	(a11.ID_ANO_LANC = a15.ID_ANO_ACUM_ANO_SALDO and 
		a11.ID_MES_LANC = (a15.ID_MES_ACUM_ANO_SALDO - 1))
		join	WD_CELULA_ORCAMENTARIA	a16
		  on 	(a11.ID_ANO_LANC = a16.ID_ANO_CEOR and 
		a11.ID_CELULA_ORCAMENTARIA_SK = a16.ID_CELULA_ORCAMENTARIA_SK)
		join	WD_FONTE_RECURSO_DETA	a17
		  on 	(a11.ID_FONTE_RECURSO_DETA = a17.ID_FONTE_RECURSO_DETA)
		join	WD_UO_EXERCICIO	a18
		  on 	(a11.ID_ANO_LANC = a18.ID_ANO and 
		a11.ID_UO = a18.ID_UO)
		join	WD_ORGAO_EXERCICIO	a19
		  on 	(a18.ID_ANO = a19.ID_ANO and 
		a18.ID_ORGAO_UO = a19.ID_ORGAO)
		join	WD_ORGAO_SUPE_EXERCICIO	a110
		  on 	(a19.ID_ANO = a110.ID_ANO and 
		a19.ID_ORGAO_SUPE = a110.ID_ORGAO_SUPE)
		join	WD_UG_EXERCICIO	a111
		  on 	(a11.ID_ANO_LANC = a111.ID_ANO and 
		a11.ID_UG_EXEC = a111.ID_UG)
		join	WD_ORGAO_EXERCICIO	a112
		  on 	(a111.ID_ANO = a112.ID_ANO and 
		a111.ID_ORGAO_UG = a112.ID_ORGAO)
		join	WD_ORGAO_SUPE_EXERCICIO	a113
		  on 	(a112.ID_ANO = a113.ID_ANO and 
		a112.ID_ORGAO_SUPE = a113.ID_ORGAO_SUPE)
		join	WD_MES	a114
		  on 	(a15.ID_ANO = a114.ID_ANO and 
		a15.ID_MES = a114.ID_MES)
	where	(a11.ID_ORCA_FISCAL_ORGAO_EXEC_H in (0)
	 and a114.SG_MES_COMPLETO = 'MAR/2019'
	 and a113.ID_ORGAO_MAXI in (32000)
	 and a14.ID_ITEM_INFORMACAO in (61)
	 and a13.ID_ANO = a114.ID_ANO
	 and a13.ID_MES = a114.ID_MES)
	group by	a113.ID_ORGAO_MAXI,
		a110.ID_ORGAO_MAXI,
		a16.ID_IN_RESULTADO_EOF,
		a16.ID_IN_PRSE_CEOR,
		a11.ID_PROGRAMA_PT,
		a11.ID_DOCUMENTO_CCOR,
		a15.ID_ANO,
		a15.ID_MES,
		a14.ID_ITEM_INFORMACAO,
		a11.ID_GRUPO_DESPESA_NADE,
		a17.ID_FONTE_RECURSO,
		a16.SN_EXCECAO_DECRETO,
		a11.ID_ELEMENTO_DESPESA_NADE,
		a11.ID_DOCUMENTO_LANC,
		a11.ID_ANO_LANC,
		a11.ID_ACAO_PT
	)	pa11
	full outer join	(select	a113.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
		a110.ID_ORGAO_MAXI  ID_ORGAO_MAXI0,
		a16.ID_IN_RESULTADO_EOF  ID_IN_RESULTADO_EOF,
		a16.ID_IN_PRSE_CEOR  ID_IN_PRSE_CEOR,
		a11.ID_PROGRAMA_PT  ID_PROGRAMA_PT,
		a11.ID_DOCUMENTO_CCOR  ID_DOCUMENTO,
		a15.ID_ANO  ID_ANO_LANC,
		a15.ID_MES  ID_MES_LANC,
		a14.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
		a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
		a17.ID_FONTE_RECURSO  ID_FONTE_RECURSO,
		a16.SN_EXCECAO_DECRETO  SN_EXCECAO_DECRETO,
		a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
		a11.ID_DOCUMENTO_LANC  ID_DOCUMENTO0,
		a11.ID_ANO_LANC  ID_ANO_EMISSAO_DOC,
		a11.ID_ACAO_PT  ID_ACAO_PT,
		sum(((a11.VA_MOVIMENTO_LIQUIDO * a14.IN_OPERACAO_EXPRESSAO) * a13.PE_TAXA))  SALDORITEMINFORMAO
	from	WF_LANCAMENTO	a11
		join	WD_MOEDA	a12
		  on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
		join	WD_TAXA_CAMBIO_MENSAL	a13
		  on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
		join	WD_ITEM_DECODIFICADO_CCON	a14
		  on 	(a11.ID_ANO_LANC = a14.ID_ANO_ITEM_CONTA and 
		a11.ID_CONTA_CONTABIL_LANC = a14.ID_CONTA_CONTABIL)
		join	WA_MES_ACUM	a15
		  on 	(a11.ID_ANO_LANC = a15.ID_ANO_ACUM_ANO_SALDO and 
		a11.ID_MES_LANC = a15.ID_MES_ACUM_ANO_SALDO)
		join	WD_CELULA_ORCAMENTARIA	a16
		  on 	(a11.ID_ANO_LANC = a16.ID_ANO_CEOR and 
		a11.ID_CELULA_ORCAMENTARIA_SK = a16.ID_CELULA_ORCAMENTARIA_SK)
		join	WD_FONTE_RECURSO_DETA	a17
		  on 	(a11.ID_FONTE_RECURSO_DETA = a17.ID_FONTE_RECURSO_DETA)
		join	WD_UO_EXERCICIO	a18
		  on 	(a11.ID_ANO_LANC = a18.ID_ANO and 
		a11.ID_UO = a18.ID_UO)
		join	WD_ORGAO_EXERCICIO	a19
		  on 	(a18.ID_ANO = a19.ID_ANO and 
		a18.ID_ORGAO_UO = a19.ID_ORGAO)
		join	WD_ORGAO_SUPE_EXERCICIO	a110
		  on 	(a19.ID_ANO = a110.ID_ANO and 
		a19.ID_ORGAO_SUPE = a110.ID_ORGAO_SUPE)
		join	WD_UG_EXERCICIO	a111
		  on 	(a11.ID_ANO_LANC = a111.ID_ANO and 
		a11.ID_UG_EXEC = a111.ID_UG)
		join	WD_ORGAO_EXERCICIO	a112
		  on 	(a111.ID_ANO = a112.ID_ANO and 
		a111.ID_ORGAO_UG = a112.ID_ORGAO)
		join	WD_ORGAO_SUPE_EXERCICIO	a113
		  on 	(a112.ID_ANO = a113.ID_ANO and 
		a112.ID_ORGAO_SUPE = a113.ID_ORGAO_SUPE)
		join	WD_MES	a114
		  on 	(a15.ID_ANO = a114.ID_ANO and 
		a15.ID_MES = a114.ID_MES)
	where	(a11.ID_ORCA_FISCAL_ORGAO_EXEC_H in (0)
	 and a114.SG_MES_COMPLETO = 'MAR/2019'
	 and a113.ID_ORGAO_MAXI in (32000)
	 and a14.ID_ITEM_INFORMACAO in (61)
	 and a13.ID_ANO = a114.ID_ANO
	 and a13.ID_MES = a114.ID_MES)
	group by	a113.ID_ORGAO_MAXI,
		a110.ID_ORGAO_MAXI,
		a16.ID_IN_RESULTADO_EOF,
		a16.ID_IN_PRSE_CEOR,
		a11.ID_PROGRAMA_PT,
		a11.ID_DOCUMENTO_CCOR,
		a15.ID_ANO,
		a15.ID_MES,
		a14.ID_ITEM_INFORMACAO,
		a11.ID_GRUPO_DESPESA_NADE,
		a17.ID_FONTE_RECURSO,
		a16.SN_EXCECAO_DECRETO,
		a11.ID_ELEMENTO_DESPESA_NADE,
		a11.ID_DOCUMENTO_LANC,
		a11.ID_ANO_LANC,
		a11.ID_ACAO_PT
	)	pa12
	  on 	(pa11.ID_ACAO_PT = pa12.ID_ACAO_PT and 
	pa11.ID_ANO_EMISSAO_DOC = pa12.ID_ANO_EMISSAO_DOC and 
	pa11.ID_ANO_LANC = pa12.ID_ANO_LANC and 
	pa11.ID_DOCUMENTO = pa12.ID_DOCUMENTO and 
	pa11.ID_DOCUMENTO0 = pa12.ID_DOCUMENTO0 and 
	pa11.ID_ELEMENTO_DESPESA_NADE = pa12.ID_ELEMENTO_DESPESA_NADE and 
	pa11.ID_FONTE_RECURSO = pa12.ID_FONTE_RECURSO and 
	pa11.ID_GRUPO_DESPESA_NADE = pa12.ID_GRUPO_DESPESA_NADE and 
	pa11.ID_IN_PRSE_CEOR = pa12.ID_IN_PRSE_CEOR and 
	pa11.ID_IN_RESULTADO_EOF = pa12.ID_IN_RESULTADO_EOF and 
	pa11.ID_ITEM_INFORMACAO = pa12.ID_ITEM_INFORMACAO and 
	pa11.ID_MES_LANC = pa12.ID_MES_LANC and 
	pa11.ID_ORGAO_MAXI = pa12.ID_ORGAO_MAXI and 
	pa11.ID_ORGAO_MAXI0 = pa12.ID_ORGAO_MAXI0 and 
	pa11.ID_PROGRAMA_PT = pa12.ID_PROGRAMA_PT and 
	pa11.SN_EXCECAO_DECRETO = pa12.SN_EXCECAO_DECRETO)
	join	WD_ACAO_PT	a13
	  on 	(coalesce(pa11.ID_ACAO_PT, pa12.ID_ACAO_PT) = a13.ID_ACAO_PT)
	join	WD_ELEMENTO_DESPESA_NADE	a14
	  on 	(coalesce(pa11.ID_ELEMENTO_DESPESA_NADE, pa12.ID_ELEMENTO_DESPESA_NADE) = a14.ID_ELEMENTO_DESPESA_NADE)
	join	WD_FONTE_RECURSO	a15
	  on 	(coalesce(pa11.ID_FONTE_RECURSO, pa12.ID_FONTE_RECURSO) = a15.ID_FONTE_RECURSO)
	join	WD_GRUPO_DESPESA_NADE	a16
	  on 	(coalesce(pa11.ID_GRUPO_DESPESA_NADE, pa12.ID_GRUPO_DESPESA_NADE) = a16.ID_GRUPO_DESPESA_NADE)
	join	WD_ITEM_INFORMACAO	a17
	  on 	(coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO) = a17.ID_ITEM_INFORMACAO)
	join	WD_MES	a18
	  on 	(coalesce(pa11.ID_ANO_LANC, pa12.ID_ANO_LANC) = a18.ID_ANO and 
	coalesce(pa11.ID_MES_LANC, pa12.ID_MES_LANC) = a18.ID_MES)
	join	WD_PROGRAMA_PT	a19
	  on 	(coalesce(pa11.ID_PROGRAMA_PT, pa12.ID_PROGRAMA_PT) = a19.ID_PROGRAMA_PT)
	join	WD_IN_PRSE_CEOR	a110
	  on 	(coalesce(pa11.ID_IN_PRSE_CEOR, pa12.ID_IN_PRSE_CEOR) = a110.ID_IN_PRSE_CEOR)
	join	WD_IN_RESULTADO_EOF_CEOR	a111
	  on 	(coalesce(pa11.ID_IN_RESULTADO_EOF, pa12.ID_IN_RESULTADO_EOF) = a111.ID_IN_RESULTADO_EOF)
	join	WD_ORGAO_MAXI	a112
	  on 	(coalesce(pa11.ID_ORGAO_MAXI0, pa12.ID_ORGAO_MAXI0) = a112.ID_ORGAO_MAXI)
	join	WD_ORGAO_MAXI	a113
	  on 	(coalesce(pa11.ID_ORGAO_MAXI, pa12.ID_ORGAO_MAXI) = a113.ID_ORGAO_MAXI)
group by	coalesce(pa11.ID_DOCUMENTO0, pa12.ID_DOCUMENTO0),
	coalesce(pa11.ID_ANO_EMISSAO_DOC, pa12.ID_ANO_EMISSAO_DOC),
	coalesce(pa11.ID_DOCUMENTO, pa12.ID_DOCUMENTO),
	coalesce(pa11.ID_ORGAO_MAXI0, pa12.ID_ORGAO_MAXI0),
	coalesce(pa11.ID_FONTE_RECURSO, pa12.ID_FONTE_RECURSO),
	coalesce(pa11.ID_GRUPO_DESPESA_NADE, pa12.ID_GRUPO_DESPESA_NADE),
	coalesce(pa11.ID_ELEMENTO_DESPESA_NADE, pa12.ID_ELEMENTO_DESPESA_NADE),
	coalesce(pa11.ID_PROGRAMA_PT, pa12.ID_PROGRAMA_PT),
	coalesce(pa11.ID_ACAO_PT, pa12.ID_ACAO_PT),
	coalesce(pa11.ID_IN_RESULTADO_EOF, pa12.ID_IN_RESULTADO_EOF),
	coalesce(pa11.ID_IN_PRSE_CEOR, pa12.ID_IN_PRSE_CEOR),
	coalesce(pa11.SN_EXCECAO_DECRETO, pa12.SN_EXCECAO_DECRETO),
	coalesce(pa11.ID_ANO_LANC, pa12.ID_ANO_LANC),
	coalesce(pa11.ID_MES_LANC, pa12.ID_MES_LANC),
	coalesce(pa11.ID_ORGAO_MAXI, pa12.ID_ORGAO_MAXI),
	coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO)